project_name: SampleProject
cxx_standard: 14
include_directories:
  - include
source_files:
  - src/sample.cpp
test_files:
  - test/sample_test.cpp
libraries:
  - GTest
  - pthread
output_directory: test

# ビルドコマンド
build_commands:
  - cmake ..
  - make

# テストコマンド
test_commands:
  - ./test/exe/MyTest  # テスト実行ファイル
  - echo "テスト完了"

# 追加のカスタムコマンド（必要なら追加）
custom_commands:
  - echo "ビルドが完了しました。"
  - echo "テストを実行しています。"
